
#ubuntu 20.04
FROM ubuntu:20.04
LABEL maintainer "Ricardo Flores"
LABEL description="Docker image for local containerized dashboard"

#update Ubuntu Software repository
RUN apt update
RUN apt -y install python3-pip
RUN apt -y install vim

#add the Flask application and install requirements
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

#open ports, set environment variables, start the application.
EXPOSE 8080 
ENV PORT 8080
ENV FLASK_ENV=development
CMD exec python3 app.py